version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/chaptered-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/chaptered-web"
    schedule:
      interval: "weekly"
